##私有仓库配置
##参考https://plugins.drone.io/plugins/docker

kind: pipeline
name: default
   
  - name: greeting
    image: alpine
    commands:
      - echo hello
      - echo world

  - name: docker
    image: plugins/docker
    settings:
      insecure: true
      registry: my.icm.icu:1080
      repo: my.icm.icu:1080/library/devops-demo
      use_cache: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: ${DRONE_BUILD_NUMBER}
    when:
      event: push
      branch: master
